window.addEventListener("load",()=>{let t=()=>{var e=document.body.style;e.width="100%",e.overflow="hidden",anzhiyu.animateIn(document.getElementById("search-mask"),"to_show 0.5s"),anzhiyu.animateIn(document.querySelector("#algolia-search .search-dialog"),"titleScale 0.5s"),setTimeout(()=>{document.querySelector("#algolia-search .ais-SearchBox-input").focus()},100),document.addEventListener("keydown",function e(t){"Escape"===t.code&&(a(),document.removeEventListener("keydown",e))})},a=(anzhiyu_keyboard&&window.addEventListener("keydown",function(e){if(83==e.keyCode&&e.shiftKey)return console.info(selectTextNow),selectTextNow?(t(),(e=document.querySelector("#algolia-search-input > div > form > input")).value=selectTextNow,e.dispatchEvent(new Event("input")),setTimeout(()=>{document.querySelector("#algolia-search-input > div > form > button.ais-SearchBox-submit").click()},64)):t(),!1}),()=>{var e=document.body.style;e.width="",e.overflow="",anzhiyu.animateOut(document.querySelector("#algolia-search .search-dialog"),"search_close .5s"),anzhiyu.animateOut(document.getElementById("search-mask"),"to_hide 0.5s")}),e=()=>{document.querySelector("#search-button > .search").addEventListener("click",t),document.getElementById("search-mask").addEventListener("click",a),document.querySelector("#algolia-search .search-close-button").addEventListener("click",a)};let s=e=>{if(""===e)return"";var t=e.indexOf("<mark>");let a=t-30,i=t+120,n="",o="";return a<=0?(a=0,i=140):n="...",i>e.length?i=e.length:o="...",n+e.substring(a,i)+o};var i=GLOBAL_CONFIG.algolia;if(!(i.appId&&i.apiKey&&i.indexName))return console.error("Algolia setting is invalid!");var n=instantsearch({indexName:i.indexName,searchClient:algoliasearch(i.appId,i.apiKey),searchFunction(e){e.state.query&&(document.getElementById("algolia-hits").innerHTML='<div class="anzhiyufont anzhiyu-icon-spinner anzhiyu-spin"></div>',e.search())}}),i=instantsearch.widgets.configure({hitsPerPage:i.hits.per_page||5}),o=instantsearch.widgets.searchBox({container:"#algolia-search-input",showReset:!1,showSubmit:!1,placeholder:GLOBAL_CONFIG.algolia.languages.input_placeholder,showLoadingIndicator:!0,searchOnEnterKeyPressOnly:!0,searchAsYouType:!1}),l=instantsearch.widgets.hits({container:"#algolia-hits",templates:{item(e){var t=e.permalink||GLOBAL_CONFIG.root+e.path,a=e._highlightResult,i=a.contentStripTruncate?s(a.contentStripTruncate.value):a.contentStrip?s(a.contentStrip.value):a.content?s(a.content.value):"",n=e.tags;let o=`
          <div class="search-result">
            <a href="${t}" class="algolia-hit-item-link">
            ${a.title.value||"no-title"}
            </a>
            <p class="algolia-hit-item-content">${i}</p>
            <div class="search-result-tags">
        `;for(let e=0;e<n.length;e++)o+=`<a class="tag-list" href="/tags/${n[e]}/">#${n[e]}</a>`;o+=`
          </div>
        </div>`;e=document.querySelector("#algolia-hits .anzhiyu-spin");return e&&(e.style.display="none"),setTimeout(()=>{document.querySelector("#algolia-search .ais-SearchBox-input").focus()},100),o},empty:function(e){var t=document.querySelector("#algolia-hits .anzhiyu-spin");return console.info(t),t&&(t.style.display="none"),setTimeout(()=>{document.querySelector("#algolia-search .ais-SearchBox-input").focus()},100),'<div id="algolia-hits-empty">'+GLOBAL_CONFIG.algolia.languages.hits_empty.replace(/\$\{query}/,e.query)+"</div>"}}}),r=instantsearch.widgets.stats({container:"#algolia-info > .algolia-stats",templates:{text:function(e){return""+GLOBAL_CONFIG.algolia.languages.hits_stats.replace(/\$\{hits}/,e.nbHits).replace(/\$\{time}/,e.processingTimeMS)}}}),c=instantsearch.widgets.poweredBy({container:"#algolia-info > .algolia-poweredBy"}),u=instantsearch.widgets.pagination({container:"#algolia-pagination",totalPages:5,templates:{first:'<i class="anzhiyufont anzhiyu-icon-angle-double-left"></i>',last:'<i class="anzhiyufont anzhiyu-icon-angle-double-right"></i>',previous:'<i class="anzhiyufont anzhiyu-icon-angle-left"></i>',next:'<i class="anzhiyufont anzhiyu-icon-angle-right"></i>'}});n.addWidgets([i,o,l,r,c,u]),n.start(),e(),document.getElementById("search-mask").addEventListener("click",a),document.querySelector("#algolia-search .search-close-button").addEventListener("click",a),document.querySelector("#menu-search").addEventListener("click",function(){rm.hideRightMenu(),t();var e=document.querySelector("#algolia-search-input > div > form > input");e.value=selectTextNow,e.dispatchEvent(new Event("input")),setTimeout(()=>{document.querySelector("#algolia-search-input > div > form > button.ais-SearchBox-submit").click()},64)}),window.addEventListener("pjax:complete",()=>{"block"===getComputedStyle(document.querySelector("#algolia-search .search-dialog")).display&&a(),e()}),window.pjax&&n.on("render",()=>{window.pjax.refresh(document.getElementById("algolia-hits"))})});